services:
  kinetic:
    build:
      context: .
      dockerfile: kinetic_6dof.dockerfile
    network_mode: "host"
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
